### ISSUE TITLE
need some screen shots.

### ISSUE THREAD

**Issue by johndpope** [Ponup/thiefcatcher#2]

**Comment by santiagolizardo** [comment]
Hi @johndpope ; You can find some screenshots of the game attached to this ticket now. In terms of compiling on High Sierra, I am not sure what the problem is as it's working on my MBP which also runs High Sierra.
Can you open a new ticket with additional info about the problem(s) you are seeing at compile time?
Thanks! 

![screen shot 2018-06-27 at 20 46 39](https://user-images.githubusercontent.com/220190/41995997-6b4108c8-7a4b-11e8-9650-3da4e734a65c.png)
![screen shot 2018-06-27 at 20 45 37](https://user-images.githubusercontent.com/220190/41995998-6b5df032-7a4b-11e8-8175-27a18525dc10.png)
![screen shot 2018-06-27 at 20 45 28](https://user-images.githubusercontent.com/220190/41996000-6b7a8c92-7a4b-11e8-8710-218c1047e576.png)
![screen shot 2018-06-27 at 20 44 46](https://user-images.githubusercontent.com/220190/41996001-6b991298-7a4b-11e8-830b-52ce47adf485.png)
![screen shot 2018-06-27 at 20 44 15](https://user-images.githubusercontent.com/220190/41996002-6bb7259e-7a4b-11e8-8943-ec4904e422f7.png)
